# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0003_category_image_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
