# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0006_auto_20190304_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_location',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
